OPTIONS (SKIP=1, DIRECT=TRUE)
LOAD DATA
INFILE '01_ORG_UNITS.csv'
APPEND
INTO TABLE org_units
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    ORG_UNIT_ID,
    ORG_UNIT_CODE CHAR,
    ORG_UNIT_NAME CHAR,
    PARENT_ORG_UNIT_ID,
    STATUS CHAR
)
