OPTIONS (SKIP=1, DIRECT=TRUE)
LOAD DATA
INFILE '02_COST_CENTERS.csv'
APPEND
INTO TABLE cost_centers
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    COST_CENTER_ID,
    COST_CENTER_CODE CHAR,
    COST_CENTER_NAME CHAR,
    ORG_UNIT_ID,
    MANAGER_NAME CHAR,
    STATUS CHAR
)
