OPTIONS (SKIP=1, DIRECT=TRUE)
LOAD DATA
INFILE '03_BUDGET_PERIODS.csv'
APPEND
INTO TABLE budget_periods
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    PERIOD_ID,
    PERIOD_CODE CHAR,
    PERIOD_NAME CHAR,
    FISCAL_YEAR,
    PERIOD_NUM,
    QUARTER_NUM,
    START_DATE DATE "YYYY-MM-DD",
    END_DATE DATE "YYYY-MM-DD",
    PERIOD_TYPE CHAR,
    STATUS CHAR
)
