OPTIONS (SKIP=1, DIRECT=TRUE)
LOAD DATA
INFILE '04_EXPENSE_CATEGORIES.csv'
APPEND
INTO TABLE expense_categories
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    EXPENSE_CATEGORY_ID,
    CATEGORY_CODE CHAR,
    CATEGORY_NAME CHAR,
    CATEGORY_GROUP CHAR,
    STATUS CHAR
)
