OPTIONS (SKIP=1, DIRECT=TRUE)
LOAD DATA
INFILE '05_BUDGET_ALLOCATIONS.csv'
APPEND
INTO TABLE budget_allocations
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    BUDGET_ALLOCATION_ID,
    PERIOD_ID,
    COST_CENTER_ID,
    EXPENSE_CATEGORY_ID,
    BUDGET_AMOUNT,
    CURRENCY_CODE CHAR,
    BUDGET_VERSION CHAR,
    APPROVAL_STATUS CHAR
)
