OPTIONS (SKIP=1, DIRECT=TRUE)
LOAD DATA
INFILE '06_ACTUAL_EXPENSES.csv'
APPEND
INTO TABLE actual_expenses
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    ACTUAL_EXPENSE_ID,
    EXPENSE_DATE DATE "YYYY-MM-DD",
    PERIOD_ID,
    COST_CENTER_ID,
    EXPENSE_CATEGORY_ID,
    VENDOR_NAME CHAR,
    DESCRIPTION CHAR,
    ACTUAL_AMOUNT,
    CURRENCY_CODE CHAR,
    INVOICE_NUM CHAR
)
