PROMPT Creating BUDGET user

CREATE USER budget IDENTIFIED BY budget
  DEFAULT TABLESPACE users
  TEMPORARY TABLESPACE temp
  QUOTA UNLIMITED ON users;

GRANT CREATE SESSION TO budget;
GRANT CREATE TABLE TO budget;
GRANT CREATE VIEW TO budget;
GRANT CREATE SEQUENCE TO budget;
GRANT CREATE SYNONYM TO budget;
GRANT CREATE PROCEDURE TO budget;
GRANT UNLIMITED TABLESPACE TO budget;
