PROMPT Running all DDL files in order
@@00_CREATE_BUDGET_USER.sql
CONNECT budget/budget@//localhost:1521/FREEPDB1
@@01_ORG_UNITS.sql
@@02_COST_CENTERS.sql
@@03_BUDGET_PERIODS.sql
@@04_EXPENSE_CATEGORIES.sql
@@05_BUDGET_ALLOCATIONS.sql
@@06_ACTUAL_EXPENSES.sql
@@07_VW_BUDGET_VS_ACTUAL.sql
@@08_CREATE_SYNONYM.sql
