SET ECHO ON
SET FEEDBACK ON
SET VERIFY OFF
SET PAGESIZE 200
SET LINESIZE 220

ALTER SESSION SET CURRENT_SCHEMA = BUDGET;

PROMPT =============================================
PROMPT 16_STAGE2_SQL_CHECKLIST.sql
PROMPT =============================================

PROMPT
PROMPT ===== 1. TABLE EXISTENCE =====
SELECT table_name
FROM   user_tables
WHERE  table_name IN (
  'ORG_UNITS',
  'COST_CENTERS',
  'BUDGET_PERIODS',
  'EXPENSE_CATEGORIES',
  'BUDGET_ALLOCATIONS',
  'ACTUAL_EXPENSES'
)
ORDER BY table_name;

PROMPT
PROMPT ===== 2. ROW COUNTS =====
SELECT 'ORG_UNITS'           AS table_name, COUNT(*) AS row_count FROM ORG_UNITS
UNION ALL
SELECT 'COST_CENTERS',       COUNT(*) FROM COST_CENTERS
UNION ALL
SELECT 'BUDGET_PERIODS',     COUNT(*) FROM BUDGET_PERIODS
UNION ALL
SELECT 'EXPENSE_CATEGORIES', COUNT(*) FROM EXPENSE_CATEGORIES
UNION ALL
SELECT 'BUDGET_ALLOCATIONS', COUNT(*) FROM BUDGET_ALLOCATIONS
UNION ALL
SELECT 'ACTUAL_EXPENSES',    COUNT(*) FROM ACTUAL_EXPENSES
ORDER BY 1;

PROMPT
PROMPT ===== 3. PRIMARY KEY NULL CHECK =====
SELECT 'ORG_UNITS.ORG_UNIT_ID'                    AS check_name, COUNT(*) AS bad_rows FROM ORG_UNITS           WHERE ORG_UNIT_ID IS NULL
UNION ALL
SELECT 'COST_CENTERS.COST_CENTER_ID',             COUNT(*) FROM COST_CENTERS       WHERE COST_CENTER_ID IS NULL
UNION ALL
SELECT 'BUDGET_PERIODS.PERIOD_ID',                COUNT(*) FROM BUDGET_PERIODS     WHERE PERIOD_ID IS NULL
UNION ALL
SELECT 'EXPENSE_CATEGORIES.EXPENSE_CATEGORY_ID',  COUNT(*) FROM EXPENSE_CATEGORIES WHERE EXPENSE_CATEGORY_ID IS NULL
UNION ALL
SELECT 'BUDGET_ALLOCATIONS.BUDGET_ALLOCATION_ID', COUNT(*) FROM BUDGET_ALLOCATIONS WHERE BUDGET_ALLOCATION_ID IS NULL
UNION ALL
SELECT 'ACTUAL_EXPENSES.ACTUAL_EXPENSE_ID',       COUNT(*) FROM ACTUAL_EXPENSES    WHERE ACTUAL_EXPENSE_ID IS NULL
ORDER BY 1;

PROMPT
PROMPT ===== 4. UNIQUE BUSINESS KEY CHECKS =====
SELECT 'ORG_UNITS.ORG_UNIT_CODE duplicates' AS check_name, COUNT(*) AS duplicate_groups
FROM (
  SELECT ORG_UNIT_CODE
  FROM   ORG_UNITS
  GROUP  BY ORG_UNIT_CODE
  HAVING COUNT(*) > 1
)
UNION ALL
SELECT 'COST_CENTERS.COST_CENTER_CODE duplicates', COUNT(*)
FROM (
  SELECT COST_CENTER_CODE
  FROM   COST_CENTERS
  GROUP  BY COST_CENTER_CODE
  HAVING COUNT(*) > 1
)
UNION ALL
SELECT 'BUDGET_PERIODS.PERIOD_CODE duplicates', COUNT(*)
FROM (
  SELECT PERIOD_CODE
  FROM   BUDGET_PERIODS
  GROUP  BY PERIOD_CODE
  HAVING COUNT(*) > 1
)
UNION ALL
SELECT 'EXPENSE_CATEGORIES.CATEGORY_CODE duplicates', COUNT(*)
FROM (
  SELECT CATEGORY_CODE
  FROM   EXPENSE_CATEGORIES
  GROUP  BY CATEGORY_CODE
  HAVING COUNT(*) > 1
)
UNION ALL
SELECT 'BUDGET_ALLOCATIONS business grain duplicates', COUNT(*)
FROM (
  SELECT PERIOD_ID, COST_CENTER_ID, EXPENSE_CATEGORY_ID, BUDGET_VERSION
  FROM   BUDGET_ALLOCATIONS
  GROUP  BY PERIOD_ID, COST_CENTER_ID, EXPENSE_CATEGORY_ID, BUDGET_VERSION
  HAVING COUNT(*) > 1
)
ORDER BY 1;

PROMPT
PROMPT ===== 5. FK LOGICAL ORPHAN CHECKS =====
SELECT 'COST_CENTERS -> ORG_UNITS' AS check_name, COUNT(*) AS orphan_rows
FROM   COST_CENTERS c
WHERE  c.ORG_UNIT_ID IS NOT NULL
AND    NOT EXISTS (
         SELECT 1
         FROM   ORG_UNITS o
         WHERE  o.ORG_UNIT_ID = c.ORG_UNIT_ID
       )
UNION ALL
SELECT 'ORG_UNITS parent -> ORG_UNITS', COUNT(*)
FROM   ORG_UNITS c
WHERE  c.PARENT_ORG_UNIT_ID IS NOT NULL
AND    NOT EXISTS (
         SELECT 1
         FROM   ORG_UNITS p
         WHERE  p.ORG_UNIT_ID = c.PARENT_ORG_UNIT_ID
       )
UNION ALL
SELECT 'BUDGET_ALLOCATIONS -> BUDGET_PERIODS', COUNT(*)
FROM   BUDGET_ALLOCATIONS b
WHERE  NOT EXISTS (
         SELECT 1
         FROM   BUDGET_PERIODS p
         WHERE  p.PERIOD_ID = b.PERIOD_ID
       )
UNION ALL
SELECT 'BUDGET_ALLOCATIONS -> COST_CENTERS', COUNT(*)
FROM   BUDGET_ALLOCATIONS b
WHERE  NOT EXISTS (
         SELECT 1
         FROM   COST_CENTERS c
         WHERE  c.COST_CENTER_ID = b.COST_CENTER_ID
       )
UNION ALL
SELECT 'BUDGET_ALLOCATIONS -> EXPENSE_CATEGORIES', COUNT(*)
FROM   BUDGET_ALLOCATIONS b
WHERE  NOT EXISTS (
         SELECT 1
         FROM   EXPENSE_CATEGORIES e
         WHERE  e.EXPENSE_CATEGORY_ID = b.EXPENSE_CATEGORY_ID
       )
UNION ALL
SELECT 'ACTUAL_EXPENSES -> BUDGET_PERIODS', COUNT(*)
FROM   ACTUAL_EXPENSES a
WHERE  NOT EXISTS (
         SELECT 1
         FROM   BUDGET_PERIODS p
         WHERE  p.PERIOD_ID = a.PERIOD_ID
       )
UNION ALL
SELECT 'ACTUAL_EXPENSES -> COST_CENTERS', COUNT(*)
FROM   ACTUAL_EXPENSES a
WHERE  NOT EXISTS (
         SELECT 1
         FROM   COST_CENTERS c
         WHERE  c.COST_CENTER_ID = a.COST_CENTER_ID
       )
UNION ALL
SELECT 'ACTUAL_EXPENSES -> EXPENSE_CATEGORIES', COUNT(*)
FROM   ACTUAL_EXPENSES a
WHERE  NOT EXISTS (
         SELECT 1
         FROM   EXPENSE_CATEGORIES e
         WHERE  e.EXPENSE_CATEGORY_ID = a.EXPENSE_CATEGORY_ID
       )
ORDER BY 1;

PROMPT
PROMPT ===== 6. BASIC VALUE CHECKS =====
SELECT 'BUDGET_ALLOCATIONS negative budget rows' AS check_name, COUNT(*) AS bad_rows
FROM   BUDGET_ALLOCATIONS
WHERE  BUDGET_AMOUNT < 0
UNION ALL
SELECT 'ACTUAL_EXPENSES negative actual rows', COUNT(*)
FROM   ACTUAL_EXPENSES
WHERE  ACTUAL_AMOUNT < 0
ORDER BY 1;

PROMPT
PROMPT ===== 7. VIEW CHECK =====
SELECT COUNT(*) AS vw_budget_vs_actual_rows
FROM   VW_BUDGET_VS_ACTUAL;

PROMPT
PROMPT ===== 8. SAMPLE BUSINESS QUERY =====
SELECT
    PERIOD_CODE,
    ORG_UNIT_NAME,
    SUM(BUDGET_AMOUNT) AS total_budget,
    SUM(ACTUAL_AMOUNT) AS total_actual,
    SUM(VARIANCE_AMOUNT) AS total_variance
FROM   VW_BUDGET_VS_ACTUAL
GROUP  BY PERIOD_CODE, ORG_UNIT_NAME
ORDER  BY PERIOD_CODE, ORG_UNIT_NAME
FETCH FIRST 20 ROWS ONLY;

PROMPT
PROMPT ===== END OF CHECKLIST =====
