SET ECHO ON
SET FEEDBACK ON
SET HEADING ON
SET LINESIZE 250
SET PAGESIZE 500
SET LONG 50000
SET LONGCHUNKSIZE 50000
SET SERVEROUTPUT ON
SET VERIFY OFF
SET TRIMSPOOL ON

SPOOL data_load_validation_output.txt

PROMPT =========================================================
PROMPT DATA VALIDATION AND BASELINE QUERIES FOR BUDGET SCHEMA
PROMPT =========================================================

PROMPT
PROMPT === SESSION CONTEXT ===
SHOW USER
SELECT SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA FROM DUAL;

ALTER SESSION SET CURRENT_SCHEMA = BUDGET;

PROMPT
PROMPT === SESSION CONTEXT AFTER ALTER SESSION ===
SHOW USER
SELECT SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA FROM DUAL;

PROMPT
PROMPT === OBJECT EXISTENCE CHECK ===
COLUMN OBJECT_NAME FORMAT A30
COLUMN OBJECT_TYPE FORMAT A20

SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
FROM ALL_OBJECTS
WHERE OWNER = 'BUDGET'
AND OBJECT_NAME IN (
    'ORG_UNITS',
    'COST_CENTERS', 
    'BUDGET_PERIODS',
    'EXPENSE_CATEGORIES',
    'BUDGET_ALLOCATIONS',
    'ACTUAL_EXPENSES',
    'VW_BUDGET_VS_ACTUAL'
)
ORDER BY OBJECT_TYPE, OBJECT_NAME;

PROMPT
PROMPT === ROW COUNTS ===
SELECT 'ORG_UNITS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM ORG_UNITS
UNION ALL
SELECT 'COST_CENTERS', COUNT(*) FROM COST_CENTERS
UNION ALL
SELECT 'BUDGET_PERIODS', COUNT(*) FROM BUDGET_PERIODS
UNION ALL
SELECT 'EXPENSE_CATEGORIES', COUNT(*) FROM EXPENSE_CATEGORIES
UNION ALL
SELECT 'BUDGET_ALLOCATIONS', COUNT(*) FROM BUDGET_ALLOCATIONS
UNION ALL
SELECT 'ACTUAL_EXPENSES', COUNT(*) FROM ACTUAL_EXPENSES;

PROMPT
PROMPT === DUPLICATE CHECKS: PRIMARY KEYS ===
SELECT ORG_UNIT_ID, COUNT(*) AS CNT
FROM ORG_UNITS
GROUP BY ORG_UNIT_ID
HAVING COUNT(*) > 1;

SELECT COST_CENTER_ID, COUNT(*) AS CNT
FROM COST_CENTERS
GROUP BY COST_CENTER_ID
HAVING COUNT(*) > 1;

SELECT PERIOD_ID, COUNT(*) AS CNT
FROM BUDGET_PERIODS
GROUP BY PERIOD_ID
HAVING COUNT(*) > 1;

SELECT EXPENSE_CATEGORY_ID, COUNT(*) AS CNT
FROM EXPENSE_CATEGORIES
GROUP BY EXPENSE_CATEGORY_ID
HAVING COUNT(*) > 1;

SELECT BUDGET_ALLOCATION_ID, COUNT(*) AS CNT
FROM BUDGET_ALLOCATIONS
GROUP BY BUDGET_ALLOCATION_ID
HAVING COUNT(*) > 1;

SELECT ACTUAL_EXPENSE_ID, COUNT(*) AS CNT
FROM ACTUAL_EXPENSES
GROUP BY ACTUAL_EXPENSE_ID
HAVING COUNT(*) > 1;

PROMPT
PROMPT === DUPLICATE CHECKS: BUSINESS KEYS ===
SELECT ORG_UNIT_CODE, COUNT(*) AS CNT
FROM ORG_UNITS
GROUP BY ORG_UNIT_CODE
HAVING COUNT(*) > 1;

SELECT COST_CENTER_CODE, COUNT(*) AS CNT
FROM COST_CENTERS
GROUP BY COST_CENTER_CODE
HAVING COUNT(*) > 1;

SELECT PERIOD_CODE, COUNT(*) AS CNT
FROM BUDGET_PERIODS
GROUP BY PERIOD_CODE
HAVING COUNT(*) > 1;

SELECT CATEGORY_CODE, COUNT(*) AS CNT
FROM EXPENSE_CATEGORIES
GROUP BY CATEGORY_CODE
HAVING COUNT(*) > 1;

SELECT PERIOD_ID, COST_CENTER_ID, EXPENSE_CATEGORY_ID, BUDGET_VERSION, COUNT(*) AS CNT
FROM BUDGET_ALLOCATIONS
GROUP BY PERIOD_ID, COST_CENTER_ID, EXPENSE_CATEGORY_ID, BUDGET_VERSION
HAVING COUNT(*) > 1;

PROMPT
PROMPT === ORPHAN CHECKS ===
SELECT COUNT(*) AS ORPHAN_COST_CENTERS
FROM COST_CENTERS CC
LEFT JOIN ORG_UNITS OU
  ON OU.ORG_UNIT_ID = CC.ORG_UNIT_ID
WHERE OU.ORG_UNIT_ID IS NULL;

SELECT COUNT(*) AS ORPHAN_BA_PERIODS
FROM BUDGET_ALLOCATIONS BA
LEFT JOIN BUDGET_PERIODS BP
  ON BP.PERIOD_ID = BA.PERIOD_ID
WHERE BP.PERIOD_ID IS NULL;

SELECT COUNT(*) AS ORPHAN_BA_COST_CENTERS
FROM BUDGET_ALLOCATIONS BA
LEFT JOIN COST_CENTERS CC
  ON CC.COST_CENTER_ID = BA.COST_CENTER_ID
WHERE CC.COST_CENTER_ID IS NULL;

SELECT COUNT(*) AS ORPHAN_BA_CATEGORIES
FROM BUDGET_ALLOCATIONS BA
LEFT JOIN EXPENSE_CATEGORIES EC
  ON EC.EXPENSE_CATEGORY_ID = BA.EXPENSE_CATEGORY_ID
WHERE EC.EXPENSE_CATEGORY_ID IS NULL;

SELECT COUNT(*) AS ORPHAN_AE_PERIODS
FROM ACTUAL_EXPENSES AE
LEFT JOIN BUDGET_PERIODS BP
  ON BP.PERIOD_ID = AE.PERIOD_ID
WHERE BP.PERIOD_ID IS NULL;

SELECT COUNT(*) AS ORPHAN_AE_COST_CENTERS
FROM ACTUAL_EXPENSES AE
LEFT JOIN COST_CENTERS CC
  ON CC.COST_CENTER_ID = AE.COST_CENTER_ID
WHERE CC.COST_CENTER_ID IS NULL;

SELECT COUNT(*) AS ORPHAN_AE_CATEGORIES
FROM ACTUAL_EXPENSES AE
LEFT JOIN EXPENSE_CATEGORIES EC
  ON EC.EXPENSE_CATEGORY_ID = AE.EXPENSE_CATEGORY_ID
WHERE EC.EXPENSE_CATEGORY_ID IS NULL;

PROMPT
PROMPT === DOMAIN / VALUE CHECKS ===
SELECT COUNT(*) AS INVALID_ORG_UNIT_STATUS
FROM ORG_UNITS
WHERE STATUS NOT IN ('ACTIVE', 'INACTIVE');

SELECT COUNT(*) AS INVALID_COST_CENTER_STATUS
FROM COST_CENTERS
WHERE STATUS NOT IN ('ACTIVE', 'INACTIVE');

SELECT COUNT(*) AS INVALID_PERIOD_TYPE
FROM BUDGET_PERIODS
WHERE PERIOD_TYPE NOT IN ('MONTH', 'QUARTER', 'YEAR');

SELECT COUNT(*) AS INVALID_PERIOD_STATUS
FROM BUDGET_PERIODS
WHERE STATUS NOT IN ('OPEN', 'CLOSED');

SELECT COUNT(*) AS INVALID_CATEGORY_STATUS
FROM EXPENSE_CATEGORIES
WHERE STATUS NOT IN ('ACTIVE', 'INACTIVE');

SELECT COUNT(*) AS NEGATIVE_BUDGETS
FROM BUDGET_ALLOCATIONS
WHERE BUDGET_AMOUNT < 0;

SELECT COUNT(*) AS NEGATIVE_ACTUALS
FROM ACTUAL_EXPENSES
WHERE ACTUAL_AMOUNT < 0;

PROMPT
PROMPT === MASTER DATA PREVIEW ===
COLUMN ORG_UNIT_CODE FORMAT A15
COLUMN ORG_UNIT_NAME FORMAT A30
SELECT * FROM ORG_UNITS ORDER BY ORG_UNIT_ID;

COLUMN COST_CENTER_CODE FORMAT A15
COLUMN COST_CENTER_NAME FORMAT A30
COLUMN MANAGER_NAME FORMAT A20
SELECT * FROM COST_CENTERS ORDER BY COST_CENTER_ID;

COLUMN PERIOD_CODE FORMAT A10
COLUMN PERIOD_NAME FORMAT A20
SELECT * FROM BUDGET_PERIODS ORDER BY PERIOD_ID;

COLUMN CATEGORY_CODE FORMAT A15
COLUMN CATEGORY_NAME FORMAT A25
COLUMN CATEGORY_GROUP FORMAT A15
SELECT * FROM EXPENSE_CATEGORIES ORDER BY EXPENSE_CATEGORY_ID;

PROMPT
PROMPT === FACT DATA PREVIEW ===
SELECT *
FROM BUDGET_ALLOCATIONS
ORDER BY BUDGET_ALLOCATION_ID
FETCH FIRST 20 ROWS ONLY;

SELECT *
FROM ACTUAL_EXPENSES
ORDER BY ACTUAL_EXPENSE_ID
FETCH FIRST 20 ROWS ONLY;

PROMPT
PROMPT === RELATIONSHIP CHECK ===
COLUMN ORG_UNIT_NAME FORMAT A30
SELECT CC.COST_CENTER_CODE,
       CC.COST_CENTER_NAME,
       OU.ORG_UNIT_NAME
FROM COST_CENTERS CC
JOIN ORG_UNITS OU
  ON OU.ORG_UNIT_ID = CC.ORG_UNIT_ID
ORDER BY CC.COST_CENTER_CODE;

PROMPT
PROMPT === VIEW PREVIEW ===
COLUMN PERIOD_NAME FORMAT A20
COLUMN COST_CENTER_NAME FORMAT A30
COLUMN CATEGORY_NAME FORMAT A25
SELECT *
FROM VW_BUDGET_VS_ACTUAL
ORDER BY PERIOD_CODE, ORG_UNIT_NAME, COST_CENTER_NAME, CATEGORY_NAME
FETCH FIRST 30 ROWS ONLY;

PROMPT
PROMPT === BASELINE QUERY 1: BUDGET VS ACTUAL BY ORG UNIT ===
SELECT ORG_UNIT_NAME,
       SUM(BUDGET_AMOUNT) AS TOTAL_BUDGET,
       SUM(ACTUAL_AMOUNT) AS TOTAL_ACTUAL,
       SUM(VARIANCE_AMOUNT) AS TOTAL_VARIANCE
FROM VW_BUDGET_VS_ACTUAL
GROUP BY ORG_UNIT_NAME
ORDER BY ORG_UNIT_NAME;

PROMPT
PROMPT === BASELINE QUERY 2: OVER BUDGET CASES ===
SELECT PERIOD_CODE,
       ORG_UNIT_NAME,
       COST_CENTER_NAME,
       CATEGORY_NAME,
       BUDGET_AMOUNT,
       ACTUAL_AMOUNT,
       VARIANCE_AMOUNT
FROM VW_BUDGET_VS_ACTUAL
WHERE ACTUAL_AMOUNT > BUDGET_AMOUNT
ORDER BY PERIOD_CODE, ORG_UNIT_NAME, COST_CENTER_NAME, CATEGORY_NAME;

PROMPT
PROMPT === BASELINE QUERY 3: BUDGET VS ACTUAL BY PERIOD ===
SELECT PERIOD_CODE,
       SUM(BUDGET_AMOUNT) AS TOTAL_BUDGET,
       SUM(ACTUAL_AMOUNT) AS TOTAL_ACTUAL,
       SUM(VARIANCE_AMOUNT) AS TOTAL_VARIANCE
FROM VW_BUDGET_VS_ACTUAL
GROUP BY PERIOD_CODE
ORDER BY PERIOD_CODE;

PROMPT
PROMPT === BASELINE QUERY 4: BUDGET VS ACTUAL BY COST CENTER ===
SELECT COST_CENTER_CODE,
       COST_CENTER_NAME,
       SUM(BUDGET_AMOUNT) AS TOTAL_BUDGET,
       SUM(ACTUAL_AMOUNT) AS TOTAL_ACTUAL,
       SUM(VARIANCE_AMOUNT) AS TOTAL_VARIANCE
FROM VW_BUDGET_VS_ACTUAL
GROUP BY COST_CENTER_CODE, COST_CENTER_NAME
ORDER BY COST_CENTER_CODE;

PROMPT
PROMPT === BASELINE QUERY 5: BUDGET VS ACTUAL BY CATEGORY ===
SELECT CATEGORY_NAME,
       SUM(BUDGET_AMOUNT) AS TOTAL_BUDGET,
       SUM(ACTUAL_AMOUNT) AS TOTAL_ACTUAL,
       SUM(VARIANCE_AMOUNT) AS TOTAL_VARIANCE
FROM VW_BUDGET_VS_ACTUAL
GROUP BY CATEGORY_NAME
ORDER BY CATEGORY_NAME;

PROMPT
PROMPT === COMMENTS / METADATA CHECK ===
COLUMN TABLE_NAME FORMAT A25
COLUMN COLUMN_NAME FORMAT A25
COLUMN COMMENTS FORMAT A80

SELECT owner, table_name, comments
FROM all_tab_comments
WHERE owner = 'BUDGET'
  AND table_name IN (
    'ORG_UNITS',
    'COST_CENTERS',
    'BUDGET_PERIODS',
    'EXPENSE_CATEGORIES',
    'BUDGET_ALLOCATIONS',
    'ACTUAL_EXPENSES'
  )
ORDER BY table_name;

PROMPT
PROMPT =========================================================
PROMPT END OF VALIDATION
PROMPT OUTPUT WRITTEN TO 10_DATA_VALIDATION_AND_BASELINE.log
PROMPT =========================================================

SPOOL OFF
EXIT